# Generated by Django 6.0.3 on 2026-04-08 09:55

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='OfficeLocation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='地點名稱')),
                ('latitude', models.DecimalField(decimal_places=6, max_digits=9, verbose_name='緯度')),
                ('longitude', models.DecimalField(decimal_places=6, max_digits=9, verbose_name='經度')),
                ('radius_meters', models.IntegerField(default=100, verbose_name='有效半徑（公尺）')),
                ('is_active', models.BooleanField(default=True, verbose_name='啟用')),
            ],
            options={
                'verbose_name': '公司地點',
                'verbose_name_plural': '公司地點',
            },
        ),
        migrations.CreateModel(
            name='ReminderSetting',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('work_start_time', models.TimeField(default='09:00', verbose_name='標準上班時間')),
                ('work_end_time', models.TimeField(default='18:00', verbose_name='標準下班時間')),
                ('late_reminder_minutes', models.IntegerField(default=30, verbose_name='逾時提醒分鐘數')),
                ('lunch_limit_minutes', models.IntegerField(default=60, verbose_name='午休上限分鐘')),
                ('enabled', models.BooleanField(default=True, verbose_name='啟用提醒')),
            ],
            options={
                'verbose_name': '提醒設定',
                'verbose_name_plural': '提醒設定',
            },
        ),
        migrations.CreateModel(
            name='AuditLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action', models.CharField(choices=[('create', '新增'), ('update', '修改'), ('delete', '刪除')], max_length=10, verbose_name='動作')),
                ('target_model', models.CharField(max_length=50, verbose_name='目標 Model')),
                ('target_id', models.IntegerField(verbose_name='目標 ID')),
                ('changes', models.JSONField(default=dict, verbose_name='變更內容')),
                ('timestamp', models.DateTimeField(auto_now_add=True, verbose_name='操作時間')),
                ('actor', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='操作者')),
            ],
            options={
                'verbose_name': '稽核日誌',
                'verbose_name_plural': '稽核日誌',
                'ordering': ['-timestamp'],
            },
        ),
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('employee_id', models.CharField(max_length=20, unique=True, verbose_name='工號')),
                ('department', models.CharField(max_length=50, verbose_name='部門')),
                ('phone', models.CharField(blank=True, max_length=20, verbose_name='電話')),
                ('line_user_id', models.CharField(blank=True, max_length=50, null=True, unique=True, verbose_name='LINE User ID')),
                ('rfid_uid', models.CharField(blank=True, max_length=20, null=True, unique=True, verbose_name='RFID 卡號')),
                ('employment_type', models.CharField(choices=[('monthly', '月薪制'), ('hourly', '時薪制')], default='monthly', max_length=10, verbose_name='薪資類型')),
                ('monthly_salary', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='月薪')),
                ('hourly_rate', models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True, verbose_name='時薪')),
                ('fuel_daily_allowance', models.DecimalField(decimal_places=2, default=0, max_digits=8, verbose_name='每日油費補貼')),
                ('is_delivery', models.BooleanField(default=False, verbose_name='是否為送貨員')),
                ('labor_insurance_amount', models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True, verbose_name='勞保自負月額')),
                ('health_insurance_amount', models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True, verbose_name='健保自負月額')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='employee', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': '員工',
                'verbose_name_plural': '員工',
            },
        ),
        migrations.CreateModel(
            name='DeliveryTask',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(verbose_name='任務日期')),
                ('order', models.IntegerField(verbose_name='第幾站')),
                ('customer_name', models.CharField(max_length=100, verbose_name='客戶名稱')),
                ('address', models.CharField(max_length=200, verbose_name='地址')),
                ('target_lat', models.DecimalField(decimal_places=6, max_digits=9, verbose_name='目標緯度')),
                ('target_lng', models.DecimalField(decimal_places=6, max_digits=9, verbose_name='目標經度')),
                ('radius_meters', models.IntegerField(default=100, verbose_name='有效半徑（公尺）')),
                ('status', models.CharField(choices=[('pending', '待出發'), ('arrived', '已到達'), ('completed', '已完成')], default='pending', max_length=15, verbose_name='狀態')),
                ('arrived_at', models.DateTimeField(blank=True, null=True, verbose_name='到達時間')),
                ('completed_at', models.DateTimeField(blank=True, null=True, verbose_name='完成時間')),
                ('note', models.TextField(blank=True, verbose_name='備註')),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='delivery_tasks', to='attendance.employee', verbose_name='送貨員')),
            ],
            options={
                'verbose_name': '送貨任務',
                'verbose_name_plural': '送貨任務',
                'ordering': ['date', 'order'],
            },
        ),
        migrations.CreateModel(
            name='BindingToken',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('token', models.CharField(default=uuid.uuid4, max_length=64, unique=True, verbose_name='綁定碼')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('expires_at', models.DateTimeField(verbose_name='有效期限')),
                ('used', models.BooleanField(default=False, verbose_name='已使用')),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='binding_tokens', to='attendance.employee', verbose_name='員工')),
            ],
            options={
                'verbose_name': '綁定 Token',
                'verbose_name_plural': '綁定 Token',
            },
        ),
        migrations.CreateModel(
            name='TaskCheckIn',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('check_type', models.CharField(choices=[('arrive', '到達'), ('complete', '完成')], max_length=10, verbose_name='打卡類型')),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('latitude', models.DecimalField(decimal_places=6, max_digits=9, verbose_name='緯度')),
                ('longitude', models.DecimalField(decimal_places=6, max_digits=9, verbose_name='經度')),
                ('distance_meters', models.IntegerField(verbose_name='距目標距離（公尺）')),
                ('is_valid', models.BooleanField(verbose_name='在有效範圍內')),
                ('task', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='checkins', to='attendance.deliverytask', verbose_name='任務')),
            ],
            options={
                'verbose_name': '任務打卡',
                'verbose_name_plural': '任務打卡',
            },
        ),
        migrations.CreateModel(
            name='AttendanceRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('record_type', models.CharField(choices=[('clock_in', '上班打卡'), ('break_start', '午休開始'), ('break_end', '午休結束'), ('clock_out', '下班打卡')], max_length=15, verbose_name='打卡類型')),
                ('timestamp', models.DateTimeField(auto_now_add=True, verbose_name='打卡時間')),
                ('latitude', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True, verbose_name='緯度')),
                ('longitude', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True, verbose_name='經度')),
                ('is_valid', models.BooleanField(default=True, verbose_name='GPS 驗證通過')),
                ('distance_meters', models.IntegerField(blank=True, null=True, verbose_name='距公司距離（公尺）')),
                ('source', models.CharField(choices=[('line', 'LINE Bot'), ('rfid', 'RFID')], default='line', max_length=10, verbose_name='打卡來源')),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='records', to='attendance.employee', verbose_name='員工')),
            ],
            options={
                'verbose_name': '打卡紀錄',
                'verbose_name_plural': '打卡紀錄',
                'ordering': ['-timestamp'],
                'indexes': [models.Index(fields=['employee', 'timestamp'], name='attendance__employe_d2a742_idx')],
            },
        ),
        migrations.CreateModel(
            name='MonthlyAllowance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('year', models.IntegerField(verbose_name='年')),
                ('month', models.IntegerField(verbose_name='月')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='加給金額')),
                ('note', models.TextField(blank=True, verbose_name='備註')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='建立者')),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='allowances', to='attendance.employee', verbose_name='員工')),
            ],
            options={
                'verbose_name': '特殊加給',
                'verbose_name_plural': '特殊加給',
                'unique_together': {('employee', 'year', 'month')},
            },
        ),
    ]
