# Generated by Django 6.0.3 on 2026-04-11 19:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attendance', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('customer_id', models.CharField(max_length=20, unique=True, verbose_name='客戶編號')),
                ('name', models.CharField(max_length=100, verbose_name='客戶名稱')),
                ('address', models.CharField(max_length=200, verbose_name='地址')),
                ('phone', models.CharField(blank=True, max_length=20, verbose_name='電話')),
                ('lat', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True, verbose_name='緯度')),
                ('lng', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True, verbose_name='經度')),
                ('is_active', models.BooleanField(default=True, verbose_name='啟用')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新時間')),
            ],
        ),
    ]
