# Generated by Django 6.0.3 on 2026-04-11 19:51

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attendance', '0002_customer'),
    ]

    operations = [
        migrations.AddField(
            model_name='deliverytask',
            name='customer',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='attendance.customer', verbose_name='客戶'),
        ),
    ]
