# Generated by Django 6.0.3 on 2026-04-11 19:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('attendance', '0003_deliverytask_customer'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='deliverytask',
            name='radius_meters',
        ),
        migrations.RemoveField(
            model_name='deliverytask',
            name='target_lat',
        ),
        migrations.RemoveField(
            model_name='deliverytask',
            name='target_lng',
        ),
        migrations.DeleteModel(
            name='TaskCheckIn',
        ),
    ]
