# Generated by Django 6.0.3 on 2026-04-11 20:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attendance', '0004_remove_deliverytask_radius_meters_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='deliverytask',
            name='is_urgent',
            field=models.BooleanField(default=False, verbose_name='急單'),
        ),
    ]
