# Generated by Django 6.0.3 on 2026-04-11 20:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attendance', '0005_deliverytask_is_urgent'),
    ]

    operations = [
        migrations.AlterField(
            model_name='deliverytask',
            name='is_urgent',
            field=models.BooleanField(default=False, verbose_name='急單'),
        ),
    ]
