# Generated by Django 6.0.3 on 2026-04-12 15:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attendance', '0006_alter_deliverytask_is_urgent'),
    ]

    operations = [
        migrations.AddField(
            model_name='employee',
            name='work_start_time',
            field=models.TimeField(blank=True, null=True, verbose_name='上班時間'),
        ),
    ]
