# Generated by Django 6.0.3 on 2026-04-13 13:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attendance', '0007_employee_work_start_time'),
    ]

    operations = [
        migrations.AddField(
            model_name='employee',
            name='work_end_time',
            field=models.TimeField(blank=True, null=True, verbose_name='下班時間'),
        ),
    ]
