# Generated by Django 6.0.3 on 2026-04-13 15:32

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attendance', '0008_employee_work_end_time'),
    ]

    operations = [
        migrations.AlterField(
            model_name='attendancerecord',
            name='timestamp',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='打卡時間'),
        ),
    ]
