# Generated by Django 6.0.3 on 2026-04-14 14:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('attendance', '0009_alter_attendancerecord_timestamp'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ReminderSetting',
        ),
    ]
