# Generated by Django 6.0.3 on 2026-04-22 15:10

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attendance', '0011_customer_phone_max50'),
    ]

    operations = [
        migrations.AddField(
            model_name='employee',
            name='remind_enabled',
            field=models.BooleanField(default=True, verbose_name='啟用打卡提醒'),
        ),
        migrations.AddField(
            model_name='employee',
            name='work_days',
            field=models.CharField(default='0,1,2,3,4', help_text='例：0,1,2,3,4 代表週一至週五', max_length=20, verbose_name='工作日（0=週一…6=週日，逗號分隔）'),
        ),
        migrations.CreateModel(
            name='LeaveRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(verbose_name='請假日期')),
                ('reason', models.CharField(blank=True, max_length=100, verbose_name='原因')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='leave_records', to='attendance.employee', verbose_name='員工')),
            ],
            options={
                'verbose_name': '請假紀錄',
                'verbose_name_plural': '請假紀錄',
                'ordering': ['-date'],
                'unique_together': {('employee', 'date')},
            },
        ),
    ]
