# Generated by Django 6.0.3 on 2026-04-25 13:22

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attendance', '0012_add_remind_and_leave'),
    ]

    operations = [
        migrations.CreateModel(
            name='LeaveRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dates', models.JSONField(verbose_name='請假日期')),
                ('status', models.CharField(choices=[('pending', '待審核'), ('approved', '已核准'), ('denied', '已拒絕')], default='pending', max_length=10, verbose_name='狀態')),
                ('requested_at', models.DateTimeField(auto_now_add=True, verbose_name='申請時間')),
                ('processed_at', models.DateTimeField(blank=True, null=True, verbose_name='處理時間')),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='leave_requests', to='attendance.employee', verbose_name='員工')),
            ],
            options={
                'verbose_name': '請假申請',
                'verbose_name_plural': '請假申請',
                'ordering': ['-requested_at'],
            },
        ),
    ]
