# Generated by Django 6.0.3 on 2026-04-30 04:45

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attendance', '0013_add_leave_request'),
    ]

    operations = [
        migrations.CreateModel(
            name='DeliverySession',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(verbose_name='任務日期')),
                ('started_at', models.DateTimeField(blank=True, null=True, verbose_name='出發時間')),
                ('finished_at', models.DateTimeField(blank=True, null=True, verbose_name='完成時間')),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='delivery_sessions', to='attendance.employee', verbose_name='送貨員')),
            ],
            options={
                'verbose_name': '送貨行程',
                'verbose_name_plural': '送貨行程',
                'ordering': ['-date'],
                'unique_together': {('employee', 'date')},
            },
        ),
    ]
