# Generated by Django 6.0.3 on 2026-04-30 05:42

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attendance', '0014_add_delivery_session'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='deliverysession',
            options={'ordering': ['-date', 'trip_number'], 'verbose_name': '送貨行程', 'verbose_name_plural': '送貨行程'},
        ),
        migrations.AlterUniqueTogether(
            name='deliverysession',
            unique_together=set(),
        ),
        migrations.AddField(
            model_name='deliverysession',
            name='pushed_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='推播時間'),
        ),
        migrations.AddField(
            model_name='deliverysession',
            name='trip_number',
            field=models.PositiveSmallIntegerField(default=1, verbose_name='趟次'),
        ),
        migrations.AddField(
            model_name='deliverytask',
            name='session',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='tasks', to='attendance.deliverysession', verbose_name='所屬趟次'),
        ),
        migrations.AlterUniqueTogether(
            name='deliverysession',
            unique_together={('employee', 'date', 'trip_number')},
        ),
    ]
