# Generated by Django 6.0.3 on 2026-05-05 06:56

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attendance', '0015_trip_number_and_session_fk'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='LocationCorrectionRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('requested_at', models.DateTimeField(auto_now_add=True, verbose_name='申請時間')),
                ('old_lat', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True, verbose_name='原緯度')),
                ('old_lng', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True, verbose_name='原經度')),
                ('new_lat', models.DecimalField(decimal_places=6, max_digits=9, verbose_name='新緯度')),
                ('new_lng', models.DecimalField(decimal_places=6, max_digits=9, verbose_name='新經度')),
                ('note', models.TextField(blank=True, verbose_name='備註')),
                ('distance_at_report', models.IntegerField(blank=True, null=True, verbose_name='回報時距離(公尺)')),
                ('status', models.CharField(choices=[('pending', '待審核'), ('approved', '已核准'), ('rejected', '已拒絕')], default='pending', max_length=10, verbose_name='狀態')),
                ('reviewed_at', models.DateTimeField(blank=True, null=True, verbose_name='審核時間')),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='correction_requests', to='attendance.customer', verbose_name='客戶')),
                ('requested_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='correction_requests', to='attendance.employee', verbose_name='申請員工')),
                ('reviewed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reviewed_corrections', to=settings.AUTH_USER_MODEL, verbose_name='審核人')),
            ],
            options={
                'verbose_name': '座標修正申請',
                'ordering': ['-requested_at'],
            },
        ),
    ]
