# Generated by Django 6.0.3 on 2026-05-06 05:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attendance', '0016_location_correction_request'),
    ]

    operations = [
        migrations.AddField(
            model_name='deliverysession',
            name='auto_closed',
            field=models.BooleanField(default=False, verbose_name='系統自動關閉'),
        ),
    ]
