# Generated by Django 6.0.3 on 2026-05-21 09:01

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attendance', '0017_deliverysession_auto_closed'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='attendancerecord',
            name='source',
            field=models.CharField(choices=[('line', 'LINE Bot'), ('rfid', 'RFID'), ('admin', '管理員確認')], default='line', max_length=10, verbose_name='打卡來源'),
        ),
        migrations.CreateModel(
            name='AttendanceAnomalyDismissal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(verbose_name='日期')),
                ('anomaly_type', models.CharField(choices=[('clock_out', '缺下班打卡'), ('break_start', '缺午休紀錄'), ('break_end', '缺午休結束')], max_length=20, verbose_name='異常類型')),
                ('dismissed_at', models.DateTimeField(auto_now_add=True, verbose_name='標記時間')),
                ('note', models.CharField(blank=True, max_length=100, verbose_name='備註')),
                ('dismissed_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='標記人')),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='anomaly_dismissals', to='attendance.employee', verbose_name='員工')),
            ],
            options={
                'verbose_name': '出勤異常標記',
                'ordering': ['-dismissed_at'],
                'unique_together': {('employee', 'date', 'anomaly_type')},
            },
        ),
    ]
