# Generated by Django 6.0.3 on 2026-05-21 09:49

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attendance', '0018_add_attendance_anomaly_dismissal'),
    ]

    operations = [
        migrations.CreateModel(
            name='GpsConsentLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('consented_at', models.DateTimeField(auto_now_add=True, verbose_name='同意時間')),
                ('consent_version', models.CharField(max_length=20, verbose_name='條款版本')),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True, verbose_name='IP 位址')),
                ('device_info', models.CharField(blank=True, max_length=255, verbose_name='裝置資訊')),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='gps_consents', to='attendance.employee', verbose_name='員工')),
            ],
            options={
                'verbose_name': 'GPS 同意紀錄',
                'ordering': ['-consented_at'],
                'unique_together': {('employee', 'consent_version')},
            },
        ),
    ]
