# Generated by Django 6.0.3 on 2026-06-09 16:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attendance', '0019_add_gps_consent_log'),
    ]

    operations = [
        migrations.AddField(
            model_name='deliverysession',
            name='planned_drive_minutes',
            field=models.FloatField(blank=True, null=True, verbose_name='ORS預估行車分鐘'),
        ),
    ]
